# -*- coding: utf-8 -*-
"""Malicious URL Detector with Machine Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qYwT9ZUcQ1zidrZEVk8pDBYvrGUKRARk
"""

!python --version

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Simulated dataset
data = {
    "URL": [
        "http://free-money.com",
        "https://secure.bank.com",
        "http://click-here-now.ru",
        "https://github.com",
        "http://malicious-site.biz"
    ],
    "IsMalicious": [1, 0, 1, 0, 1]
}

df = pd.DataFrame(data)
df['url_length'] = df['URL'].apply(len)
df['has_https'] = df['URL'].apply(lambda x: int("https" in x))

X = df[['url_length', 'has_https']]
y = df['IsMalicious']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Test prediction
sample = {"URL": "https://secure-login.com"}
length = len(sample['URL'])
has_https = int("https" in sample['URL'])

prediction = model.predict([[length, has_https]])
print("🔍 Prediction for", sample['URL'])
print("⚠️ Malicious" if prediction[0] == 1 else "✅ Safe")